FROM anibali/pytorch:cuda-10.0
RUN conda install notebook==5.7.4 pandas==0.24.1
RUN pip install pytorch-pretrained-bert==0.6.1 pytorch-ignite==0.1.2
RUN python -c "from pytorch_pretrained_bert.tokenization import BertTokenizer; BertTokenizer.from_pretrained('bert-base-uncased', cache_dir='/home/user/.pytorch_pretrained_bert')"
RUN python -c "from pytorch_pretrained_bert.modeling import BertForSequenceClassification; BertForSequenceClassification.from_pretrained('bert-base-uncased', cache_dir='/home/user/.pytorch_pretrained_bert')"
CMD ["ipython"]
